### ISSUE TITLE
Some materials may be useful

### ISSUE THREAD

**Issue by DerrickXuNu** [Little-Podi/Collaborative_Perception#1]
Hi Shenyuan, great work for summarizing collaborative perception! This repo will be very useful! 

I have some other materials that may be useful to the community, please consider adding them to your repo if you find them valuable.

[Talk] Cooperative Driving Automation -- Simulation and Perception. Link: https://course.zhidx.com/c/MmQ1YWUyMzM1M2I3YzVlZjE1NzM=
[Library] [ITSC2021[OpenCDA:  A simulation framework that supports full-stack cooperative driving automation, including cooperative perception, localization, planning, and control. Link: https://github.com/ucla-mobility/OpenCDA

**Comment by Little-Podi** [comment]
Hi Runsheng, I am delighted to receive your interest and recognition. I have learned a lot from the high-quality materials you recommended. They have been added to this repo now so that more people can benefit from them. Thanks!

**Comment by DerrickXuNu** [comment]
Thanks!
